PARTICIPANTS, CONTESTS = map(int, input().split())
CONTESTS_SCORE_ARRAY = list(map(int, input().split()))
ADVANCED_PARTICIPANTS = 0
for i in range(PARTICIPANTS):
    if CONTESTS_SCORE_ARRAY[i] >= CONTESTS_SCORE_ARRAY[CONTESTS-1] and CONTESTS_SCORE_ARRAY[i]>0:
        ADVANCED_PARTICIPANTS = ADVANCED_PARTICIPANTS+1
print(ADVANCED_PARTICIPANTS)